django_exercise_answer/django_exercise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ex2/', include('ex2.urls')),
    path('ex3/', include('ex3.urls')),
    path('ex4/', include('ex4.urls')),
    path('ex5/', include('ex5.urls')),
    path('ex7/', include('ex7.urls')),
    path('ex8/', include('ex8.urls')),
]

django_exercise_answer/ex2/urls.py
from django.urls import path
from . import views

app_name = "ex2"

urlpatterns = [
    path('hello1/', views.hello1, name='hello1'),
    path('hello2/', views.hello2, name='hello2'),
    path('hello3/', views.Hello3View.as_view(), name='hello3'),
    path('hello4/', views.hello4, name='hello4'),
]

django_exercise_answer/ex3/urls.py
from django.urls import path
from . import views

app_name = "ex3"

urlpatterns = [
    path('input1/', views.input1, name='input1'),
    path('show1/', views.show1, name='show1'),
    path('input2/<str:param1>', views.input2, name='input2'),
]

django_exercise_answer/ex3/models.py
from django.db import models

# Create your models here.

django_exercise_answer/ex3/views.py
from django.shortcuts import render

def input1(request):
    return render(request, 'input1.html')

def show1(request):
    inp = request.POST['inp']
    ctx = {
        'inp': inp,
    }
    return render(request, 'show1.html', ctx)

def input2(request, param1):
    ctx = {
        'inp': param1,
    }
    return render(request, 'show1.html', ctx)

django_exercise_answer/ex3/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>
            {% block title %}タイトル{% endblock %}
        </title>
    </head>
    <body>
        {% block content %}内容{% endblock %}
    </body>
</html>

django_exercise_answer/ex3/templates/input1.html
{% extends 'base.html' %}
{% block title %}
input1
{% endblock %}

{% block content %}
<form action="{% url 'ex3:show1' %}" method="post">
    {% csrf_token %}
    <p><input type="text" name='inp'></p>
    <p><input type="submit"></p>
</form>
{% endblock %}

django_exercise_answer/ex3/templates/show1.html
{% extends 'base.html' %}
{% block title %}
show1
{% endblock %}

{% block content %}
{{ inp }}
{% endblock %}