django_exercise_answer/django_exercise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ex2/', include('ex2.urls')),
    path('ex3/', include('ex3.urls')),
    path('ex4/', include('ex4.urls')),
    path('ex5/', include('ex5.urls')),
    path('ex7/', include('ex7.urls')),
    path('ex8/', include('ex8.urls')),
]

django_exercise_answer/ex2/urls.py
from django.urls import path
from . import views

app_name = "ex2"

urlpatterns = [
    path('hello1/', views.hello1, name='hello1'),
    path('hello2/', views.hello2, name='hello2'),
    path('hello3/', views.Hello3View.as_view(), name='hello3'),
    path('hello4/', views.hello4, name='hello4'),
]

django_exercise_answer/ex5/urls.py
from django.urls import path
from . import views

app_name = "ex5"

urlpatterns = [
    path('add_emp1/', views.add_emp1, name='add_emp1'),
    path('add_emp1_end/', views.add_emp1_end, name='add_emp1_end'),
    path('list_emp/', views.EmpListView.as_view(), name='list_emp'),
    path('detail_emp/<int:pk>', views.EmpDetailView.as_view(), name='detail_emp'),
    path('add_emp2/', views.EmpCreateView.as_view(), name='add_emp2'),
    path('update_emp/<int:pk>', views.EmpUpdateView.as_view(), name='update_emp'),
    path('update_emp_end/', views.EmpUpdateEndView.as_view(), name='update_emp_end'),
    path('delete_emp/<int:pk>', views.EmpDeleteView.as_view(), name='delete_emp'),
    path('delete_emp_end/', views.EmpDeleteEndView.as_view(), name='delete_emp_end'),
]

django_exercise_answer/ex5/models.py
from django.db import models

class Dept(models.Model):
    name = models.CharField(max_length=50)
    tel = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Emp(models.Model):
    name = models.CharField(max_length=50)
    birthday = models.DateField()
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

django_exercise_answer/ex5/forms.py
from django import forms
from .models import Emp

class EmpForm(forms.ModelForm):
    class Meta:
        model = Emp
        fields = '__all__'

django_exercise_answer/ex5/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required    # 演習8で追加
from django.contrib.auth.mixins import LoginRequiredMixin    # 演習8で追加

from .models import Emp
from .forms import EmpForm

@login_required   # 演習8で追加
def add_emp1(request):
    if request.method == 'POST':
        form = EmpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ex5:add_emp1_end')
        else:
            ctx = {
                'form': form,
            }
            return render(request, 'add_emp1.html', ctx)
    else:
        form = EmpForm()
        ctx = {
            'form': form
        }
        return render(request, 'add_emp1.html', ctx)

def add_emp1_end(request):
    return render(request, 'add_emp1_end.html')

class EmpCreateView(LoginRequiredMixin, generic.CreateView):  # 演習8で変更
# class EmpCreateView(generic.CreateView):
    template_name = 'add_emp1.html'
    model = Emp
    fields = '__all__'
    success_url = reverse_lazy('ex5:add_emp1_end')

class EmpListView(generic.ListView):
    template_name = 'list_emp.html'
    model = Emp

class EmpDetailView(generic.DetailView):
    template_name = 'detail_emp.html'
    model = Emp

class EmpUpdateView(generic.UpdateView):
    template_name = 'update_emp.html'
    model = Emp
    fields = '__all__'
    success_url = reverse_lazy('ex5:update_emp_end')

class EmpUpdateEndView(generic.TemplateView):
    template_name = 'update_emp_end.html'

class EmpDeleteView(generic.DeleteView):
    template_name = 'delete_emp.html'
    model = Emp
    success_url = reverse_lazy('ex5:delete_emp_end')

class EmpDeleteEndView(generic.TemplateView):
    template_name = 'delete_emp_end.html'

django_exercise_answer/ex5/templates/add_emp1.html
{% extends 'base.html' %}
{% block title %}add_emp1{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            <p>{{ form }}</p>
        </table>
        <p>
            <input type="submit">
        </p>
    </form>
{% endblock %}

django_exercise_answer/ex5/templates/add_emp1_end.html
{% extends 'base.html' %}
{% block title %}
add_emp1_end
{% endblock %}

{% block content %}
登録終了
{% endblock %}

django_exercise_answer/ex5/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>
            {% block title %}タイトル{% endblock %}
        </title>
    </head>
    <body>
        {% block content %}内容{% endblock %}
    </body>
</html>

django_exercise_answer/ex5/templates/delete_emp.html
{% extends 'base.html' %}
{% block title %}delete_emp{% endblock %}
{% block content %}
    <table border="1">
        <tr>
            <th>名前</th>
            <th>生年月日</th>
            <th>部署</th>
        </tr>
        <tr>
            <td>{{ object.name }}</td>
            <td>{{ object.birthday }}</td>
            <td>{{ object.dept }}</td>
        </tr>
    </table>
    <form method="post">
        {% csrf_token %}
        <p>
            <input type="submit" value="削除します">
        </p>
    </form>

{% endblock %}

django_exercise_answer/ex5/templates/delete_emp_end.html
{% extends 'base.html' %}
{% block title %}
delete_emp_end
{% endblock %}

{% block content %}
削除終了
{% endblock %}

django_exercise_answer/ex5/templates/detail_emp.html
{% extends 'base.html' %}
{% block title %}add_emp1{% endblock %}
{% block content %}
    <table border="1">
        <tr>
            <th>id</th>
            <th>名前</th>
            <th>生年月日</th>
            <th>部署</th>
        </tr>
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.name }}</td>
            <td>{{ object.birthday }}</td>
            <td>{{ object.dept }}</td>
        </tr>
    </table>
{% endblock %}

django_exercise_answer/ex5/templates/list_emp.html
{% extends 'base.html' %}
{% block title %}add_emp1{% endblock %}
{% block content %}
    <table border="1">
        <tr>
            <th>id</th>
            <th>名前</th>
            <th>生年月日</th>
            <th>部署</th>
        </tr>
        {% for obj in object_list %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>{{ obj.name }}</td>
                <td>{{ obj.birthday }}</td>
                <td>{{ obj.dept }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

django_exercise_answer/ex5/templates/top.html
{% extends 'base.html' %}
{% block title %}top{% endblock %}
{% block content %}
<a href="{% url 'ex5:list_emp' %}">一覧表示</a>
<a href="{% url 'ex5:list_emp' %}">新規追加</a>
{% endblock %}

django_exercise_answer/ex5/templates/update_emp.html
{% extends 'base.html' %}
{% block title %}update_emp1{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            <p>{{ form }}</p>
        </table>
        <p>
            <input type="submit">
        </p>
    </form>
{% endblock %}

django_exercise_answer/ex5/templates/update_emp_end.html
{% extends 'base.html' %}
{% block title %}
update_emp_end
{% endblock %}

{% block content %}
更新終了
{% endblock %}